services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./trash/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432