spring:
  application:
    name: importer

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

    hikari:
      maximum-pool-size: 64

  http:
    client:
      read-timeout: 10000
      connect-timeout: 10000
